### ISSUE TITLE
Async functions and variables

### ISSUE THREAD

**Issue by fabiofranzini** [luc-freyermuth/formula-functionizer#1]
- **I'm submitting a question**
  [ ] bug report
  [ ] feature request
  [ X] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Hi, great library! I wanted to know if there is way to call asynchronous functions. 
The context could be to have functions that make HTTP requests for example.

**Comment by luc-freyermuth** [comment]
Hello :) Sorry for the late response :)

As for today, the library does not have special support for async functions and variables.

Such a feature would be awesome and could use rxjs Observables rather than Promises to handle operations in the formula, but it also would be a huge amount of work to implement it. And I don't have enough time to allocate for the moment sadly :/

If it really is critical for you, a workaround should work for simple cases. As said in the readme, you can add your own custom functions to the parser. There is no reason that should prevent your custom functions to return a promise or take a promise as an argument.

ex for returning a promise:

```ts
import { Parser } from 'formula-functionizer';
import * as formulajs from '@formulajs/formulajs';

const parser = new Parser({
  functions: {
    ...formulajs,
    DOUBLE_ASYNC: (x) => Promise.resolve(x * 2),
  },
});

const fn = parser.parse('DOUBLE_ASYNC(SUM(x, y))');

fn({ x: 4, y: 5 }).then(result => {
      console.log(result); // 18
})
```

example for working with a Promise:

```ts
import { Parser } from 'formula-functionizer';
import * as formulajs from '@formulajs/formulajs';

const parser = new Parser({
  functions: {
    ...formulajs,
    DOUBLE_ASYNC: (x) => Promise.resolve(x * 2),
    MULTIPLY_PROMISES: (x, y) => Promise.all([x, y]).then(([a, b]) => a * b)
  },
});

const fn = parser.parse('MULTIPLY_PROMISES(DOUBLE_ASYNC(x), DOUBLE_ASYNC(y))');

fn({ x: 2, y: 3 }).then(result => {
      console.log(result); // 24
})
```

**Comment by fabiofranzini** [comment]
Hello @luc-freyermuth and thanks for your reply!
I think that your demo can cover my problems to call a function in async way!

I'll try! 😀
